parameters:
  comments:
    toggleLimit: 2
  # for edit config action
  comschange_editable_config_params:
    - comments:
      - toggleLimit
  
services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Comschange\Service\:
    resource: 'services/*'
  YesWiki\Comschange\Controller\:
    resource: 'controllers/*'
 
  # replace usage of Core Comment Service by comschange one 
  # to force registration of event listeners
  # ignore if core CommentService is not existing
  YesWiki\Comschange\Service\CommentService:
    decorates: YesWiki\Core\Service\CommentService
    decoration_on_invalid: ignore
    tags:
      - { name: yeswiki.event_subscriber_alt }
    calls: 
      - registerSubscribers: []

  YesWiki\Comschange\Service\ActionsBuilderService:
    decorates: YesWiki\Aceditor\Service\ActionsBuilderService
    decoration_on_invalid: null
    arguments:
      $parentActionsBuilderService: '@.inner'