parameters:
  comments:
    toggleLimit: 2
  # for edit config action
  comschange_editable_config_params:
    - comments:
      - toggleLimit

services:
  _defaults:
    autowire: true
    public: true

  # Allows to use controllers as services
  YesWiki\Comschange\Controller\:
    resource: 'controllers/*'